service: lambda-image-search
provider:
  name: aws
  region: us-east-1
  runtime: python3.9
  # stage: prod

functions:
  search_image:
    handler: handler.search_image
    events:
      - http:
          path: /search
          method: get

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin
